<!-- POPUP BEGIN -->

<div class="alert alert-dismissible popup" role="alert">
	
	<button id="close-x" type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
	
	<h1>Modal Title</h1>
	
	<hr />
	
	<div class="popup-body">
		<p>Panel content Panel content Panel
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.
		Panel contentPanel contentPanel content.</p>
		
		<img src="img/popup_thumbnail.jpg" />
	</div> <!-- .popup-body -->
	
	<hr />
	
	<button id="close-button" type="button" class="btn btn-success" data-dismiss="alert" aria-label="Close">Fechar</button>

</div><!-- .popup -->

<!-- POPUP END -->